#!/usr/bin/env python3
import logging, coloredlogs, warnings
import datetime
import argparse
import geojson
import functools, copy
import re
import zipfile
import os, sys
import requests
import json
from math import ceil, inf, sqrt

log = logging.getLogger('convert_map')
warnings.simplefilter('ignore')

from fastkml.kml import KML
from shapely.geometry import shape, Point, LineString
from shapely.ops import transform as coord_transform
import pyproj
import matplotlib as mpl

# BL'23 data:
#PLACEMENT_ENTITIES_URL = 'https://web.archive.org/web/20240506201312/https://placement.freaks.se/api/v1/mapentities'
#POWER_KML_URL = 'https://www.google.com/maps/d/kml?forcekml=1&mid=1zD_Jj58_9Lq29tYEz6X6zSc2Ag2NSP0'

PLACEMENT_ENTITIES_URL = 'https://placement.freaks.se/api/v1/mapentities'
POWER_KML_URL = 'http://www.google.com/maps/d/kml?forcekml=1&mid=1oS6UFpJMdwnm7UmkaEBRJrC3Mhp80nQ'
PLACEMENT_ROADS_URL = 'https://www.theborderland.se/map/data/bl24/roads_and_distances.geojson'
PLACEMENT_HOODS_LABELS_URL = 'https://www.theborderland.se/map/data/bl24/labels/neighbourhoods.json'
PLACEMENT_HOODS_URL = 'https://www.theborderland.se/map/data/bl24/neighbourhoods.geojson'

POWER_KML_FOLDERS = [
        'areas',
        'NORTH',
        'SOUTH',
        'EAST',
        'Not_measured_Areas',
        'Barn_and_the_hill'
        ]

POWER_ITEM_SIZE_ORDER = ['125', '63', '32', '16', '1f', 'unknown']

GRID_STYLE = {
    '125': {
        'stroke-width': 5,
        'marker-size': 5,
        },
    '63': {
        'stroke-width': 4,
        'marker-size': 4,
        },
    '32': {
        'stroke-width': 3,
        'marker-size': 3,
        },
    '16': {
        'stroke-width': 2,
        'marker-size': 2,
        },
    '1f': {
        'stroke-width': 1,
        'marker-size': 1,
        },
    'unknown': {
        'stroke-width': 5,
        'marker-size': 5,
        'marker-color': '#FF0000'
        },
    }

ENTITY_STYLE_NOISY = {
        'marker-color': '#f2495c',
        'marker-size': 3
        }

POWER_SUMMARIES = [
        ['PNS', 'PNE', 'PNW'],
        ['PNW', 'PNE'],
        ['PNS'],
        ['PSW', 'PSS'],
        ['PE'],
        ['PSC', 'PSE']
        ]

POWER_AREAS_FROM_TRAFO = [
        'PSC', 'PNS', 'PSE', 'PNE', 'PNW', 'The Villa', 'PSS', 'PSW', 'PE'
        ]

POWER_AREAS_PRIMARY = [
        'unknown',
        'PX1',
        'The Villa',
        'PSC',
        'PSE',
        'PSS',
        'PSW',
        'PE',
        'PNS',
        'PNE',
        'PNW'
        ]

GRID_CABLES_MISC = {
        'Main sub E': 63,
        'Garden Line': 63,
        'Line 23': 32,
        'Line 75': 16,
        'testline 05': 125,
        }

GRID_PDUS_MISC = {
        'Generator 35-40kva': 63,
        'Generator, 35kva': 63,
        'Transformator': 125
        }

IGNORE_ENTITIES = [
        'Offlimit',
        'The Void'
        ]

geod = pyproj.Geod(ellps="WGS84")
local_azimuthal_projection = f"+proj=aeqd +R=6371000 +units=m +lat_0=57.62377 +lon_0=14.92715"
wgs84_to_aeqd = functools.partial(
    pyproj.transform,
    pyproj.Proj('+proj=longlat +datum=WGS84 +no_defs'),
    pyproj.Proj(local_azimuthal_projection),
)

aeqd_to_wgs84 = functools.partial(
    pyproj.transform,
    pyproj.Proj(local_azimuthal_projection),
    pyproj.Proj('+proj=longlat +datum=WGS84 +no_defs'),
)

COLORMAP_PWR_HIGH = mpl.colormaps['plasma']
COLORNORM_PWR_HIGH= mpl.colors.Normalize(vmin=0, vmax=7400)
COLORMAP_PWR_LOW = mpl.colormaps['winter']
COLORNORM_PWR_LOW= mpl.colors.Normalize(vmin=0, vmax=1250)
COLORMAP_PWR_COVERAGE = mpl.colormaps['inferno']
COLORNORM_PWR_COVERAGE= mpl.colors.Normalize(vmin=0, vmax=5)
def powerneed_color(power):
    if power == 0:
        color = [0, 0, 0]
    elif power <= 1000:
        color = COLORMAP_PWR_LOW(1-COLORNORM_PWR_LOW(power), bytes=True)
    else:
        color = COLORMAP_PWR_HIGH(COLORNORM_PWR_HIGH(power), bytes=True)
    return '#'+bytes(color)[:3].hex()

def coverage_color(nr_pdus):
    return '#'+bytes(COLORMAP_PWR_HIGH(1-COLORNORM_PWR_COVERAGE(nr_pdus), bytes=True))[:3].hex()

def geojson_fixup(j, rename=None, style=None):
    if style:
        j.style = style
    for feature in j.features:
        feature.properties = {k: v for k, v in feature.properties.items() if v is not None}
        if rename:
            #feature.properties[rename] = feature.properties['Name']
            feature['id'] = feature.properties['Name']
            del(feature.properties['Name'])

    return j

def geojson_load(name, *args, **kwargs):
    j: geojson.FeatureCollection = geojson.load(open(f"BL_2024_power_grid/{name}.geojson"))
    del(j.crs)
    return geojson_fixup(j, *args, **kwargs)

def kml_to_geojson(folder, *args, **kwargs):
    j = geojson.FeatureCollection([geojson.Feature(geometry=f.geometry, properties={
        'Name': f.name,
        'description': f.description
        }) for f in folder.features()])
    return geojson_fixup(j, *args, **kwargs)

def get_powermap_kml(kmz_path):
    if kmz_path:
        try:
            with zipfile.ZipFile(kmz_path) as kmz_file:
                with kmz_file.open('doc.kml', 'r') as kml_file:
                    return kml_file.read()
        except zipfile.BadZipFile:
            with open(kmz_path, 'r') as kml_file:
                return kml_file.read()
    else:
        log.info("Fetching power map")
        return requests.get(POWER_KML_URL).content

@functools.cache
def kml_folders(kml_doc):
    kml = KML()
    kml.from_string(kml_doc)
    result = {}
    for folder in next(kml.features()).features():
        name = str(folder.name).strip().replace(' ', '_')
        log.debug(f"KML folder {name}")
        result[name] = folder

    return result

def power_item_order(item):
    return POWER_ITEM_SIZE_ORDER.index(item.properties.get('power_size', 'unknown'))

def power_item_desc(item):
    if not item:
        return None
    name = item.properties.get('Name', '')
    desc = item.properties.get('description', '')
    if desc:
        return f"{name} / {desc}"
    else:
        return name

def is_grid_feature(feature):
    name = feature.properties.get('Name')
    desc = feature.properties.get('description')
    if ((name == '1.2ha') or
        (desc and ('1ha' in desc)) or
        (name in ['HEX', 'ECLAIRE', 'THE LEMON'])):
        log.warning(f"not a grid feature: {power_item_desc(feature)}")
        return False
    return True

def find_power_area(power_areas, item):
    for area in power_areas.features:
        if shape(area.geometry).contains(item):
            return area
    return None

def find_power_area_name(power_areas, item):
    if item.type == 'Point':
        area = find_power_area(power_areas, item)
        if area:
            return area.id
        else:
            return 'unknown'
    elif item.type == 'LineString':
        line_areas = {}
        for item in item.coords:
            area_name = 'unknown'
            area = find_power_area(power_areas, Point(item))
            if area:
                area_name = area.id
            line_areas[area_name] = line_areas.setdefault(area_name, 0) + 1
        if not line_areas:
            return None
        else:
            return max(line_areas.items(), key=lambda it: it[1])[0]

def find_nearest(needle, haystack):
    best_dist = +inf
    best = None
    for item in haystack:
        dist = needle.distance(shape(item.geometry))
        if dist < best_dist:
            best_dist = dist
            best = item
    return best

@functools.cache
def get_power_areas(kml_doc):
    folders = kml_folders(kml_doc)
    j = {
            'type': 'FeatureCollection',
            'features': flatten([x.features for x in [
                kml_to_geojson(folders['areas'], rename='Area'),
                kml_to_geojson(folders['Roads'], rename='Road')
                ]])}
    result = [
            geojson.Feature(
                id='unknown',
                geometry=geojson.Polygon(),
                properties={
                    'name': 'unknown',
                    'total_power': 0,
                    'population': 0,
                    'area': 9999999
                    })
            ]
    for feature in j['features']:
        if feature.geometry.type != 'Polygon':
            continue
        log.debug(f'Area: {feature.id}')
        feature.properties['name'] = feature.id
        feature.properties['total_power'] = 0
        feature.properties['population'] = 0
        feature.properties['area'] = int(coord_transform(wgs84_to_aeqd, shape(feature.geometry)).area)
        result.append(feature)
    return geojson.FeatureCollection(result)

def power_areas_pretty_totals(power_areas):
    total_area = None
    total_power = 0
    for area in power_areas.features:
        if area.id == '8kV Pole and Transformer':
            total_area = area
            continue
        area_power = area.properties['total_power']
        if area.id in POWER_AREAS_FROM_TRAFO:
            total_power += area_power
        area.properties['total_power_kw'] = ceil(area_power/1000)
        area.properties['total_power_kw_div3'] = ceil(area_power/3/1000)
        area.properties['total_power_kw_div6'] = ceil(area_power/6/1000)
        del(area.properties['total_power'])

    if total_area:
        total_area.properties['total_power_kw'] = ceil(total_power/1000)
        total_area.properties['total_power_kw_div3'] = ceil(total_power/3/1000)
        total_area.properties['total_power_kw_div6'] = ceil(total_power/6/1000)
        del(total_area.properties['total_power'])

    return power_areas

def gen_power_areas_list(power_areas):
    result = []
    for area in power_areas.features:
        if area.properties['name'] == 'unknown' or not area.properties['total_power_kw']:
            continue
        point = shape(area.geometry).centroid.coords[0]
        result.append({
            'id': area.properties['name'],
            'lon': point[0],
            'lat': point[1],
            'total_power_kw': area.properties['total_power_kw'],
            'total_power_kw_div3': area.properties['total_power_kw_div3'],
            'total_power_kw_div6': area.properties['total_power_kw_div6'],
            })
    return result

def gen_power_areas_csv(areas, output_dir=None):
    if output_dir:
        csv = open(output_dir+"/power_areas.csv", "w")
    else:
        log.info("")
        log.info("Areas:")
        csv = sys.stdout
    
    COLUMNS = [
        'name',
        'area',
        'population',
        'total_power_kw'
        ]
    secondary = filter(lambda it: it not in POWER_AREAS_PRIMARY, areas.keys())
    for area_name in [*POWER_AREAS_PRIMARY, *secondary]:
        area = areas[area_name][0]
        props = area.properties
        if not props['total_power_kw']:
            continue
        line = ';'.join([str(props[key]) for key in COLUMNS])
        csv.write(line+'\n')
    csv.close()

def gen_grid_coverage(power_grid):
    result = []
    for item in power_grid.features:
        if item.geometry.type != 'Point':
            continue
        p = shape(item.geometry)
        poly = coord_transform(aeqd_to_wgs84,
                coord_transform(wgs84_to_aeqd, p).buffer(50, quad_segs=8))
        result.append(geojson.Feature(
            geometry=poly,
            properties={
                'name': item.properties.get('Name')
                }))
    return geojson.FeatureCollection(result)

def gen_grid_pdus_list(power_grid):
    result = []
    for item in power_grid.features:
        if item.geometry.type != 'Point':
            continue
        p = shape(item.geometry).coords[0]
        result.append({
            'name': item.properties.get('Name'),
            'lon': p[0],
            'lat': p[1],
            })
    return result

def flatten(l):
    return [item for sublist in l for item in sublist]

def line_length(feat: geojson.LineString):
    return geod.geometry_length(shape(feat.geometry))

def print_powermap_stats(power_grid):
    log.info("")
    all_cables = {}
    all_pdus = {}
    for item in power_grid.features:
        log.debug(item)
        if item.geometry.type == 'Point':
            all_pdus.setdefault(item.properties['power_size'], []).append(item)
        elif item.geometry.type == 'LineString':
            all_cables.setdefault(item.properties['power_size'], []).append(item)

    all_total_length = 0
    log.info("Cable lines:")
    for cable_type in POWER_ITEM_SIZE_ORDER:
        cables = all_cables.get(cable_type, None)
        if not cables:
            continue
        total_length = 0
        for cable in cables:
            length = line_length(cable)
            #length = math.ceil(length/25)*25
            total_length += length
            log.debug(f"    {cable.properties.get('Name'):>20}: {length:>4.0f}m")
        all_total_length += total_length
        log.info(f"  {cable_type:>3}: {total_length:,.0f}m")
    log.info(f"Total cable length: {all_total_length:,.0f}m")

    pdu_count = 0
    log.info("PDUs:")
    for pdu_type in POWER_ITEM_SIZE_ORDER:
        pdus = all_pdus.get(pdu_type, None)
        if not pdus:
            continue
        log.info(f"  PDU {pdu_type}: {len(pdus)}")
        pdu_count += len(pdus)
    log.info(f"Total: {pdu_count}")

def gen_powermap_csv(power_grid, output_dir=None):
    log.info("")
    log.info("Generating grid CSV")
    if output_dir:
        csv = open(output_dir+"/power_grid_cables.csv", "w")
    else:
        log.info("")
        log.info("Cables:")
        csv = sys.stdout

    for item in filter(lambda it: it.geometry.type == 'LineString', power_grid.features):
        props = item.properties
        length = line_length(item)
        csv.write(f"{props['power_area']};{power_item_desc(item)};{props['power_size']};{length:.0f}\n")

    if output_dir:
        csv.close()
        csv = open(output_dir+"/power_grid_pdus.csv", "w")
    else:
        log.info("")
        log.info("pdus:")
        csv = sys.stdout

    pdus = {}
    for item in filter(lambda it: it.geometry.type == 'Point', power_grid.features):
        pdus.setdefault(item.properties['power_size'], []).append(item)
    pdus_line = ';'.join([str(len(pdus.get(power_size, []))) for power_size in POWER_ITEM_SIZE_ORDER])
    csv.write(pdus_line + "\n")

@functools.cache
def get_power_grid(kml_doc):
    folders = kml_folders(kml_doc)
    features = flatten([x.features for x in [kml_to_geojson(folders[folder]) for folder in POWER_KML_FOLDERS]])
    power_areas = get_power_areas(kml_doc)

    result = []
    for feature in features:
        #log.debug(f'Power: {feature}')
        name = feature.properties['Name']
        if feature.geometry.type == 'Point':
            amps = 'unknown'
            if not is_grid_feature(feature):
                log.warning(f"skip point {power_item_desc(feature)}")
                continue
            m = re.match(r'^(\d+)\s?A?', name)
            if m:
                amps = m.groups(1)[0]
                if amps == '64':
                    amps = '63'
            elif name in GRID_PDUS_MISC:
                amps = str(GRID_PDUS_MISC[name])
            else:
                log.warning(f"can't determine PDU type: {power_item_desc(feature)}")

            feature.properties['power_size'] = amps
            feature.properties['power_area'] = find_power_area_name(power_areas, shape(feature.geometry))
            feature.properties['marker-size'] = GRID_STYLE[amps]['marker-size']
            log.debug(f"PDU: {feature.properties['power_size']} ({feature.properties['power_area']})")
        elif feature.geometry.type == 'LineString':
            amps = 'unknown'
            m = re.match(r'(\d+)\s*A?', name)
            if not m:
                m = re.match(r'(\d+)\s*A?', feature.properties.get('description', ''))
            if m:
                amps = m.groups(1)[0]
                if amps == '64':
                    amps = '63'
            elif '1f' in name:
                amps = '1f'
            elif name in GRID_CABLES_MISC:
                amps = str(GRID_CABLES_MISC[name])
            else:
                log.warning(f"can't determine cable type: {power_item_desc(feature)}")

            if amps == '230':
                amps = '1f'

            feature.properties['power_size'] = amps
            feature.properties['power_area'] = find_power_area_name(power_areas, shape(feature.geometry))
            feature.properties['stroke-width'] = GRID_STYLE[amps]['stroke-width']
            log.debug(f"Line: {feature.properties['power_size']} ({feature.properties['power_area']})")
        else:
            log.debug(f"skip {power_item_desc(feature)}")
            continue
        result.append(feature)

    return geojson.FeatureCollection(result)

def simplify_power_grid(power_grid):
    result = []
    for item in power_grid.features:
        if power_item_order(item) > 2:
             continue
        feature = copy.deepcopy(item)
        result.append(feature)
    return geojson.FeatureCollection(result)

def get_power_consumers(power_areas):
    areas = {}
    for area in power_areas.features:
        areas[area.id] = (area, [])

    j = requests.get(PLACEMENT_ENTITIES_URL).json()
    log.info(f"Fetched {len(j)} entities")
    consumers = []
    for item in j:
        if item['isDeleted']:
            continue
        gj = geojson.loads(item['geoJson'])
        name = gj.properties.get('name')
        if not name or name in IGNORE_ENTITIES:
            continue

        log.debug(gj.properties)
        nrOfPeople = int(gj.properties.get('nrOfPeople', 0) or 0)
        power = int(gj.properties.get('powerNeed', 0) or 0)
        if power == -1:
            power = 0
        elif power < 0:
            log.warning(f"Negative power: '{name}' wants {power} W, fixing up")
            power = -power
        elif power > 100000:
            log.warning(f"Unrealisticly high power need: '{name}' wants {power} W, ignoring")
            power = 0

        log.debug(f"Entity: {name}, power: {power}")

        gj.properties['nrOfPeople'] = nrOfPeople
        gj.properties['powerNeed'] = power
        for k in ['color', 'nrOfVechiles', 'additionalSqm', 'supressWarnings']:
            del(gj.properties[k])
        consumers.append(gj)

    for item in consumers:
        name = item.properties.get('name')
        item_shape = shape(item.geometry)
        power = item.properties.get('powerNeed')
        area_name = 'unknown'
        for area in power_areas.features:
            area_shape = shape(area.geometry)
            if area_shape.contains(item_shape.centroid):
                area_name = area.properties['name']
                if not item.properties.get('powerArea'):
                    item.properties['powerArea'] = area_name
                area.properties['total_power'] += item.properties['powerNeed']
                area.properties['population'] += item.properties['nrOfPeople']
                areas[area_name][1].append(item)
        if area_name == 'unknown':
            area = areas['unknown'][0]
            if item.properties['powerNeed'] > 0:
                log.warning(f"Unable to assign power area: '{name}', power: {power} W")
            item.properties['powerArea'] = area_name
            area.properties['total_power'] += item.properties['powerNeed']
            area.properties['population'] += item.properties['nrOfPeople']
            areas[area_name][1].append(item)


    return geojson.FeatureCollection(consumers), areas

def gen_consumer_markers(consumers):
    markers = []
    for item in consumers.features:
        if item.geometry.type != 'Polygon':
            continue
        point = shape(item.geometry).centroid
        nrOfPeople = int(item.properties['nrOfPeople'] or 0)
#        if int(item.properties.get('amplifiedSound', 0) or 0) >= 999:
#            markers.append(geojson.Feature(
#                geometry=point,
#                properties={
#                    'name': '[Sound] ' + item.properties['name'],
#                    **ENTITY_STYLE_NOISY
#                    }
#                ))
        if nrOfPeople > 0:
            markers.append(geojson.Feature(
                geometry=point,
                properties={
                    'name': item.properties['name'],
                    'marker-size': sqrt(nrOfPeople)*2,
                    'marker-color': powerneed_color(item.properties['powerNeed'])
                    }
                ))
    return geojson.FeatureCollection(markers)

def gen_consumer_list(consumers):
    result = []
    for item in consumers.features:
        if item.geometry.type != 'Polygon':
            continue
        if not item.properties['powerNeed']:
            continue
        point = shape(item.geometry).centroid.coords[0]
        result.append({
            'id': item.properties['name'],
            'lon': point[0],
            'lat': point[1],
            'powerNeed': item.properties['powerNeed'],
            'nrOfPeople': int(item.properties['nrOfPeople'] or 0),
            'amplifiedSound': int(item.properties['amplifiedSound'] or 0)
            })
    return result

def gen_consumer_simplified(consumers):
    result = []
    for item in consumers.features:
        feature = copy.deepcopy(item)
        if 'powerNrPDUs' in feature.properties:
            del(feature.properties['powerNrPDUs'])
        if 'powerDistance' in feature.properties:
            del(feature.properties['powerDistance'])
        if feature.properties['powerArea'] == 'unknown' and feature.properties['powerNeed'] > 0:
            feature.properties['fill'] = '#00ffff'
        else:
            feature.properties['fill'] = powerneed_color(item.properties['powerNeed'])
        result.append(feature)
    return geojson.FeatureCollection(result)

def check_consumer_coverage(consumers, power_grid):
    pdus = []
    for item in power_grid.features:
        if item.geometry.type != 'Point':
            continue
        item.properties['power_consumers_num'] = 0
        item.properties['power_consumers_kw'] = 0
        pdus.append((item, coord_transform(wgs84_to_aeqd, shape(item.geometry))))

    for item in consumers.features:
        if not item.properties['powerNeed']:
            item.properties['fill'] = coverage_color(10)
            continue
        name = item.properties['name']
        p_item = coord_transform(wgs84_to_aeqd, shape(item.geometry).centroid)

        best_distance = inf
        item.properties['powerNrPDUs'] = 0
        for pdu, p_pdu in pdus:
            distance = p_item.distance(p_pdu)
            if distance < best_distance:
                best_distance = distance
            if distance > 50:
                continue
            item.properties['powerNrPDUs'] += 1
            pdu.properties['power_consumers_num'] += 1
            pdu.properties['power_consumers_kw'] += item.properties['powerNeed']

        if best_distance > 50:
            log.warning(f"Nearest PDU is too far ({best_distance:.0f}m) for '{name}'")
            item.properties['fill'] = '#ff0000'

        item.properties['powerDistance'] = int(best_distance)
        item.properties['fill'] = coverage_color(item.properties['powerNrPDUs'])

    for pdu, _ in pdus:
        pdu.properties['power_consumers_kw'] = int(pdu.properties['power_consumers_kw']/1000)

def print_area_summary(area):
    area_name = area.properties.get('name')
    total_power = area.properties.get('total_power')
    if not total_power:
        return 0
    total_population = area.properties['population']
    area_size = area.properties['area']
    log.info(f"\t{area_name:>12} {total_power/1000:7.0f} {total_power/1000/3:7.0f} {total_power/1000/6:7.0f}  {total_population:8} {total_power/total_population:9.0f} {total_population/area_size:11.3f} ")
    return total_power

def print_consumer_stats(consumers, areas):
    log.info("")
    log.info("Power need per power area:")
    all_areas_total_power = 0
    all_consumers_total_power = sum([it.properties['powerNeed'] for it in consumers.features])
    log.info("")
    log.info(f"\t     Area       P,kW  P/3,kW  P/6,kW    people  W/person  people/m^2")
    log.info("\t---------------------------------------------------------------------")
    for area_name in POWER_AREAS_PRIMARY:
        area = areas[area_name][0]
        total_power = print_area_summary(area)
        all_areas_total_power += total_power
    log.info("\t---------------------------------------------------------------------")
    for area_name, (area, camps) in areas.items():
        if area_name in POWER_AREAS_PRIMARY:
            continue
        print_area_summary(area)
    #all_areas_total_power = sum(area_total_power.values())

    log.info("\t--------------------------------------------------------")
    log.info("\tFeed lines")
    log.info("\t------------------------------------")
    for areas_list in POWER_SUMMARIES:
        label = '+'.join(areas_list)
        power = 0
        for item in areas_list:
            power += areas[item][0].properties['total_power']
        log.info(f"\t{label:>12} {power/1000:7.0f} {power/1000/3:7.0f} {power/1000/6:7.0f}")
    log.info("")
    log.info(f"All areas total power: {all_areas_total_power/1000:.0f} kW")
    log.info(f"All consumers total power: {all_consumers_total_power/1000:.0f} kW")

    log.info("")
    log.info("Top 5 consumers per area:")
    for area_name, (area, camps) in sorted(areas.items(), key=lambda it: it[1][0].properties.get('total_power', 0), reverse=True):
        total_power = area.properties.get('total_power')
        if not total_power:
            continue
        log.info(f"\t{area_name} ({total_power/1000:.0f} kW):")
        for camp in sorted(camps, key=lambda x: x.properties['powerNeed'], reverse=True)[:5]:
            power = camp.properties['powerNeed']
            percentage = power/total_power*100
            log.info(f"\t\t'{camp.properties['name']}': {power/1000:.0f} kW / {percentage:.0f}%")

    camps_powered = list(sorted(
        filter(lambda it: it.properties['powerNeed'] > 0, consumers.features),
        key=lambda it: it.properties['powerNeed'], reverse=True))

    camps_high_usage = list(filter(lambda it: it.properties['powerNeed'] >= 3700, camps_powered))
    log.info("")
    log.info(f"Camps total: {len(consumers.features)}")
    log.info(f"Camps using power: {len(camps_powered)}")
    log.info(f"Camps using >3700W: {len(camps_high_usage)}")
    for item in camps_high_usage:
        log.info(f"\t{item.properties['name']} ({item.properties['powerArea']}) - {item.properties['powerNeed']/1000:.0f} kW")


def do_powermap_geojson(args):
    kml_doc = get_powermap_kml(args.kmz_path)
    power_grid = get_power_grid(kml_doc)
    print_powermap_stats(power_grid)
    geojson.dump(power_grid, open(args.output_dir+'/power_grid.geojson', 'w'), indent=2)

def do_powermap_csv(args):
    kml_doc = get_powermap_kml(args.kmz_path)
    power_grid = get_power_grid(kml_doc)
    gen_powermap_csv(power_grid)

def do_update_placement(args):
    kml_doc = get_powermap_kml(args.kmz_path)
    power_areas = get_power_areas(kml_doc)
    consumers, areas = get_power_consumers(power_areas)
    print_consumer_stats(consumers, areas)
    power_areas_pretty_totals(power_areas)
    geojson.dump(power_areas, open(args.output_dir+'/power_areas.geojson', 'w'), indent=2)
    geojson.dump(consumers, open(args.output_dir+'/entities.geojson', 'w'), indent=2)

    hoods = geojson.loads(requests.get(PLACEMENT_HOODS_URL).content)
    hoods_labels = geojson.loads(requests.get(PLACEMENT_HOODS_LABELS_URL).content)
    hoods.features += hoods_labels.features
    roads = geojson.loads(requests.get(PLACEMENT_ROADS_URL).content)
    hoods.features += [it for it in roads.features if it.properties.get('type') not in ['oktocamp', 'publicplease']]
    geojson.dump(hoods, open(args.output_dir+'/neighbourhoods.geojson', 'w'), indent=2)

def do_full_report(args):
    kml_doc = get_powermap_kml(args.kmz_path)
    power_areas = get_power_areas(kml_doc)
    power_grid = get_power_grid(kml_doc)

    print_powermap_stats(power_grid)

    log.info("")
    consumers, areas = get_power_consumers(power_areas)
    check_consumer_coverage(consumers, power_grid)

    log.info("")
    print_consumer_stats(consumers, areas)

    power_areas_pretty_totals(power_areas)
    geojson.dump(power_areas, open(args.output_dir+'/power_areas.geojson', 'w'), indent=2)
    json.dump(gen_power_areas_list(power_areas), open(args.output_dir+'/power_areas.json', 'w'), indent=2)
    gen_power_areas_csv(areas, args.output_dir)
    geojson.dump(power_grid, open(args.output_dir+'/power_grid.geojson', 'w'), indent=2)
    geojson.dump(simplify_power_grid(power_grid), open(args.output_dir+'/power_grid_simplified.geojson', 'w'), indent=2)
    geojson.dump(gen_grid_coverage(power_grid), open(args.output_dir+'/power_coverage.geojson', 'w'), indent=2)
    json.dump(gen_grid_pdus_list(power_grid), open(args.output_dir+'/power_pdus.json', 'w'), indent=2)
    gen_powermap_csv(power_grid, args.output_dir)

    geojson.dump(consumers, open(args.output_dir+'/entities.geojson', 'w'), indent=2)
    json.dump(gen_consumer_list(consumers), open(args.output_dir+'/entities.json', 'w'), indent=2)
    geojson.dump(gen_consumer_simplified(consumers), open(args.output_dir+'/entities_simplified.geojson', 'w'), indent=2)
    geojson.dump(gen_consumer_markers(consumers), open(args.output_dir+'/entities_markers.geojson', 'w'), indent=2)
    #geojson.dump(consumers, open(args.output_dir+'/entities_markers.geojson', 'w'), indent=2)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-r", "--report", action='store_true', default=False,
                        help="Simplify output as text report")
    parser.add_argument("-d", "--debug", action='store_true', default=False,
                        help="Enable debug")
    parser.add_argument("-o", "--output-dir", type=str, default="./map",
                                 help="Output directory")
    parser.add_argument("-k", "--kmz_path", type=str, default=None,
                                 help="KMZ file exported from googlemaps")
    actions = parser.add_subparsers(title="Action", required=True)

    act_powermap_geojson = actions.add_parser("powermap_geojson",
        help="Convert powermap to GeoJSON")
    act_powermap_geojson.set_defaults(func=do_powermap_geojson)

    act_powermap_csv = actions.add_parser("powermap_csv",
        help="Generate CSV lists of cables and PDUs")
    act_powermap_csv.set_defaults(func=do_powermap_csv)

    act_update_placement = actions.add_parser("update_placement",
        help="Update placement entities")
    act_update_placement.set_defaults(func=do_update_placement)

    act_full_report = actions.add_parser("full_report",
        help="Generate full report")
    act_full_report.set_defaults(func=do_full_report)
    args = parser.parse_args()

    if args.report:
        logging.basicConfig(
                format="%(message)s",
                level=logging.INFO
                )
        log.info(f"Generated at {datetime.datetime.utcnow()} (UTC)")
    else:
        coloredlogs.install(
                fmt="%(name)s %(levelname)s: %(message)s",
                level=logging.INFO
                )
    if args.debug:
        coloredlogs.set_level(logging.DEBUG)

    try:
        os.mkdir(args.output_dir, mode=0o755)
        log.info(f"Created output directory {args.output_dir}")
    except FileExistsError: pass

    args.func(args)

if __name__ == '__main__':
    main()
