baseURL = 'https://bl.skookum.cc/'
languageCode = 'en-us'
title = 'Borderland Power Systems'
theme = 'terminal'

[params]
  themeColor = 'green'
  centerTheme = true

[language]
  [languages.en]
    languageName = "English"
    title = "Borderland Power Systems"
    subtitle = "Energizing your dreams"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
  
  [languages.en.params.logo]
    logoText = "BL Power"
    logoHomeLink = "/"
